export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CREATE_DB_USER_START = 'CREATE_DB_USER_START';
export const CREATE_DB_USER_SUCCESS = 'CREATE_DB_USER_SUCCESS';
export const CREATE_DB_USER_FAILED = 'CREATE_DB_USER_FAILED';

export const GET_DB_USER_START = 'GET_DB_USER_START';
export const GET_DB_USER_SUCCESS = 'GET_DB_USER_SUCCESS';
export const GET_DB_USER_FAILED = 'GET_DB_USER_FAILED';

export const GET_USER_RECIPES_START = 'GET_USER_RECIPES_START';
export const GET_USER_RECIPES_SUCCESS = 'GET_USER_RECIPES_SUCCESS';
export const GET_USER_RECIPES_FAILED = 'GET_USER_RECIPES_FAILED';

export const USER_RECIPE_SELECTED = "USER_RECIPE_SELECTED";
export const INPUT_DATA_ENTERED = "INPUT_DATA_ENTERED";
export const RECIPE_DATA_ENTERED = "RECIPE_DATA_ENTERED";
export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";
export const UPDATE_RECIPE_INFO = "UPDATE_RECIPE_INFO";

export const SAVE_RECIPE_START = 'SAVE_RECIPE_START';
export const SAVE_RECIPE_SUCCESS = 'SAVE_RECIPE_SUCCESS';
export const SAVE_RECIPE_FAILED = 'SAVE_RECIPE_FAILED';

export const UPDATE_RECIPE_START = 'UPDATE_RECIPE_START';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAILED = 'UPDATE_RECIPE_FAILED';

export const DELETE_RECIPE_START = 'DELETE_RECIPE_START';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAILED = 'DELETE_RECIPE_FAILED';

export const SET_DATABASE_WEIGHTS_START = 'SET_DATABASE_WEIGHTS_START';
export const SET_DATABASE_WEIGHTS_SUCCESS = 'SET_DATABASE_WEIGHTS_SUCCESS';
export const SET_DATABASE_WEIGHTS_FAILED = 'SET_DATABASE_WEIGHTS_FAILED';
export const SET_WEIGHTS_REDUX = 'SET_WEIGHTS_REDUX';

export const GET_DATABASE_WEIGHTS_START = 'GET_DATABASE_WEIGHTS_START';
export const GET_DATABASE_WEIGHTS_SUCCESS = 'GET_DATABASE_WEIGHTS_SUCCESS';
export const GET_DATABASE_WEIGHTS_FAILED = 'GET_DATABASE_WEIGHTS_FAILED';

export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const CLEAR_FORMULA_ERROR = 'CLEAR_FORMULA_ERROR';
export const CLEAR_DATABASE_ERROR = 'CLEAR_DATABASE_ERROR';
export const CLEAR_DB_REDUX = 'CLEAR_DB_REDUX';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
export const USER_RECIPE_CLEARED = 'USER_RECIPE_CLEARED';
export const VALIDATE_RECIPES = 'VALIDATE_RECIPES';


export const MODIFY_FLAVOR_RECIPE_COUNT_REDUX = 'MODIFY_FLAVOR_RECIPE_COUNT_REDUX';
export const MODIFY_FLAVOR_RECIPE_COUNT_START = 'MODIFY_FLAVOR_RECIPE_COUNT_START';
export const MODIFY_FLAVOR_RECIPE_COUNT_SUCCESS = 'MODIFY_FLAVOR_RECIPE_COUNT_SUCCESS';
export const MODIFY_FLAVOR_RECIPE_COUNT_FAILED = 'MODIFY_FLAVOR_RECIPE_COUNT_FAILED';

export const SAVE_FLAVOR_DATA_REDUX = 'SAVE_FLAVOR_DATA_REDUX';
export const SAVE_FLAVOR_DATA_DATABASE_START = 'SAVE_FLAVOR_DATA_DATABASE_START';
export const SAVE_FLAVOR_DATA_DATABASE_SUCCESS = 'SAVE_FLAVOR_DATA_DATABASE_SUCCESS';
export const SAVE_FLAVOR_DATA_DATABASE_FAILED = 'SAVE_FLAVOR_DATA_DATABASE_FAILED';
export const GET_USER_INVENTORY_START = 'GET_USER_INVENTORY_START';
export const GET_USER_INVENTORY_SUCCESS = 'GET_USER_INVENTORY_SUCCESS';
export const GET_USER_INVENTORY_FAILED = 'GET_USER_INVENTORY_FAILED';

export const SAVE_SHOPPING_LIST_REDUX = 'SAVE_SHOPPING_LIST_REDUX';
export const SAVE_SHOPPING_LIST_DATABASE_START = 'SAVE_SHOPPING_LIST_DATABASE_START';
export const SAVE_SHOPPING_LIST_DATABASE_SUCCESS = 'SAVE_SHOPPING_LIST_DATABASE_SUCCESS';
export const SAVE_SHOPPING_LIST_DATABASE_FAILED = 'SAVE_SHOPPING_LIST_DATABASE_FAILED';
export const GET_USER_SHOPPING_LIST_START = 'GET_USER_SHOPPING_LIST_START';
export const GET_USER_SHOPPING_LIST_SUCCESS = 'GET_USER_SHOPPING_LIST_SUCCESS';
export const GET_USER_SHOPPING_LIST_FAILED = 'GET_USER_SHOPPING_LIST_FAILED';
export const CLEAR_INVENTORY_REDUX = 'CLEAR_INVENTORY_REDUX';
