export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const INPUT_DATA_ENTERED = "QUANTITY_DATA_ENTERED";
export const RECIPE_DATA_ENTERED = "RECIPE_DATA_ENTERED";
export const CHECK_INPUT_VALIDITY = "CHECK_INPUT_VALIDITY";
export const CHECK_VALIDITY_COMPARE = "CHECK_VALIDITY_COMPARE";

export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";
export const UPDATE_RECIPE_INFO = "UPDATE_RECIPE_INFO";